function [fitresult, gof] = createFit1(lamda, nsq)
%CREATEFIT1(LAMDA,NSQ)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : lamda
%      Y Output: nsq
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-May-2019 15:31:08


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( lamda, nsq );

% Set up fittype and options.
ft = fittype( 'a+b/x^2+c/x^4', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.019911247015029 0.923197561731013 0.985257632008722];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'nsq vs. lamda', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel lamda
ylabel nsq
grid on


